package generate;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * null
 * @TableName ci_account_info
 */
@Data
public class CiAccountInfo implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Integer id;

    /**
     * 关联ID
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Integer iid;

    /**
     * 
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Integer uid;

    /**
     * 客户ID
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Short buid;

    /**
     * 单号
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private String billno;

    /**
     * 
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private String billtype;

    /**
     * 单据日期
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Date billdate;

    /**
     * 结算账户ID
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Integer accid;

    /**
     * 收款金额  采购退回为正
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Double payment;

    /**
     * 结算方式ID
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Integer wayid;

    /**
     * 结算号
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private String settlement;

    /**
     * 备注
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private String remark;

    /**
     * 
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Integer transtype;

    /**
     * 
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private String transtypename;

    /**
     * 
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ci_account_info
     *
     * @mbg.generated 2022-01-10 22:33:57
     */
    private static final long serialVersionUID = 1L;
}